server:
  port: 8095
spring:
  application:
    name: comment-service
  cache:
    cache-names: comment-service-cache
    caffeine:
      spec: initialCapacity=50,maximumSize=10,expireAfterAccess=300s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka