spring:
  application:
    name: post-details-service
  datasource:
    url: jdbc:h2:file:./post_details_db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
