server:
  port: 1111
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jlkesh/bootcamp22_ms_1_config.git
          clone-on-start: true
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka